language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.6.29
  - 5.6.30
  - 7.0
  - 7.1

install:
  - sh ./bin/prepare_tests.sh

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit.xml.dist --coverage-text test

notifications:
  email:
    on_success: change
    on_failure: change